apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viking-dev-stakater-nordmart-review
  namespace: openshift-gitops
spec:
  destination:
    namespace: viking-dev
    server: 'https://kubernetes.default.svc'
  project: viking
  source:
    path: viking/stakater-nordmart-review/dev
    repoURL: 'https://github.com/stakater-lab/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
