apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <TENANT_NAME>-prod-stakater-nordmart-review
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: <TENANT_NAME>
    stakater.com/env: prod
    stakater.com/kind: prod
spec:
  destination:
    namespace: <TENANT_NAME>-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-<TENANT_NAME>/02-stakater-nordmart-review/02-prod
    repoURL: 'https://gitlab.apps.devtest.vxdqgl7u.kubeapp.cloud/<GROUP_NAME>/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  project: <TENANT_NAME>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
