apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <TENANT_NAME>-dev-stakater-nordmart-review-ui
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: <TENANT_NAME>
    stakater.com/env: dev
    stakater.com/kind: dev
spec:
  destination:
    namespace: <TENANT_NAME>-dev
    server: 'https://kubernetes.default.svc'
  project: <TENANT_NAME>
  source:
    path: 01-<TENANT_NAME>/04-stakater-nordmart-review-ui/01-dev
    repoURL: 'https://github.com/<GROUP_NAME>/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true