apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-preview-stakater-nordmart-review-api
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: preview
    stakater.com/kind: preview      
spec:
  destination:
    namespace: arsenal-build
    server: 'https://kubernetes.default.svc'
  project: arsenal
  source:
    path: arsenal/stakater-nordmart-review-api/preview
    repoURL: 'https://github.com/DESTINATION_ORG/webinar-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
