stakater-nordmart-review-api:
  application:
    deployment:
      image:
        repository: nexus-docker-stakater-nexus.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/stakater-nordmart-review-api
        tag: 1.0.0
