apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viking-build
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: viking
  source:
    path: viking/argocd-apps/build
    repoURL: 'https://github.com/stakater-lab/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
