apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viking-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: viking-dev
    server: 'https://kubernetes.default.svc'
  project: viking
  source:
    path: viking/argocd-apps/dev
    repoURL: 'https://github.com/stakater-lab/webinar-apps-gitops-config/'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
