apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <TENANT_NAME>-build-tekton-pipelines
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: <TENANT_NAME>
    stakater.com/env: build
    stakater.com/kind: build
spec:
  destination:
    namespace: <TENANT_NAME>-build
    server: 'https://kubernetes.default.svc'
  project: <TENANT_NAME>
  source:
    path: 01-<TENANT_NAME>/00-tekton-pipelines/00-build
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true