apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-backend-dev
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: team-backend/argocd-apps/dev
    repoURL: 'https://github.com/stakater-lab/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
