apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-dev
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: arsenal-dev
    server: 'https://kubernetes.default.svc'
  project: arsenal
  source:
    path: arsenal/argocd-apps/dev
    repoURL: 'https://github.com/DESTINATION_ORG/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
